//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicalShow_3rd_HandIn {
	
	
	public partial class CreateMagician {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxName;
		
		protected System.Web.UI.WebControls.Label LabelName;
		
		protected System.Web.UI.WebControls.TextBox TextBoxPassword;
		
		protected System.Web.UI.WebControls.Label LabelPassword;
		
		protected System.Web.UI.WebControls.TextBox TextBoxMagic;
		
		protected System.Web.UI.WebControls.Label LabelMagic;
		
		protected System.Web.UI.WebControls.Button ButtonAdd;
	}
}
